### ISSUE TITLE
Support for Compose Path

### ISSUE THREAD

**Issue by shubhamsinghshubham777** [mohsenoid/SvgToCompose#1]
First of all, I'd really like to appreciate your work 👏🏻 Glad that someone is trying to make such a tool.

Now, I was under the impression that since it generates Compose code, it might be supported on Jetpack Compose's PATH too. But contrary to my expectations, as we can see in the image as well, some of its commands are not.

<a href="https://ibb.co/gRzgVXn"><img src="https://i.ibb.co/FDg7VfP/Screenshot-1.png" alt="Screenshot-1" border="0"></a>

So would you please be kind enough @mohsenoid and try to add support for Jetpack Compose's PATH as well in the future? This would bring confidence to a lot of developers and motivate them to build interesting complex custom views/shapes/paths 🌟 

For a quick glance, here are the methods that are currently supported by a Compose path:

**_moveTo
relativeMoveTo
lineTo
relativeLineTo
quadraticBezierTo
relativeQuadraticBezierTo
cubicTo
relativeCubicTo
arcToRad
arcTo
addRect
addOval
addArcRad
addArc
addRoundRect
addPath
close_**

**Comment by mohsenoid** [comment]
Hey @shubhamsinghshubham777, Thanks for reaching out and testing the code and asking for improvements.

I forgot to write in the readme that I stopped working on this repo cause I learned that there is another project as an Android Studio plugin which does that:
https://github.com/DevSrSouza/svg-to-compose

I hope you find it useful.
I will close this issue and Update the readme.
